esphome:
  name: sprinklers
  platform: ESP32
  board: esp32dev

# Enable logging
logger:
#  level: VERY_VERBOSE
  
# Enable Home Assistant API
api:

ota:
  password: "87c2ef4fb33a7005eb9e1e85169f8de6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  reboot_timeout: 24h

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sprinklers Fallback Hotspot"
    password: "f7T3bxJQWdO3"

captive_portal:

i2c:
  sda: GPIO17
  scl: GPIO16

font:
  - file: "fonts/LiberationMono-Regular.ttf"
    id: my_font
    size: 20

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(my_font), "Hello World!");

switch:
  - platform: gpio
    pin: GPIO14
    id: sprinklers_1
    name: "IrriZone 1"
    icon: mdi:sprinkler-variant
    on_turn_on:
      - switch.turn_off: sprinklers_2
      - switch.turn_off: sprinklers_3
      - switch.turn_off: sprinklers_4
      - switch.turn_off: sprinklers_5
      - switch.turn_off: sprinklers_6
#      - output.turn_on: zone1
      - delay: 
          minutes: 60
      - switch.turn_off: sprinklers_1
#    on_turn_off:
#      - output.turn_off: zone1

  - platform: gpio
    pin: GPIO12
    id: sprinklers_2
    name: "IrriZone 2"
    icon: mdi:sprinkler-variant
    on_turn_on:
      - switch.turn_off: sprinklers_1
      - switch.turn_off: sprinklers_3
      - switch.turn_off: sprinklers_4
      - switch.turn_off: sprinklers_5
      - switch.turn_off: sprinklers_6
      - delay: 
          minutes: 60
      - switch.turn_off: sprinklers_2

  - platform: gpio
    pin: GPIO13
    id: sprinklers_3
    name: "IrriZone 3"
    icon: mdi:sprinkler-variant
    on_turn_on:
      - switch.turn_off: sprinklers_1
      - switch.turn_off: sprinklers_2
      - switch.turn_off: sprinklers_4
      - switch.turn_off: sprinklers_5
      - switch.turn_off: sprinklers_6
      - delay: 
          minutes: 60
      - switch.turn_off: sprinklers_3

  - platform: gpio
    pin: GPIO15
    id: sprinklers_4
    name: "IrriZone 4"
    icon: mdi:sprinkler-variant
    on_turn_on:
      - switch.turn_off: sprinklers_1
      - switch.turn_off: sprinklers_2
      - switch.turn_off: sprinklers_3
      - switch.turn_off: sprinklers_5
      - switch.turn_off: sprinklers_6
      - delay: 
          minutes: 60
      - switch.turn_off: sprinklers_4

  - platform: gpio
    pin: GPIO2
    id: sprinklers_5
    name: "IrriZone 5"
    icon: mdi:sprinkler-variant
    on_turn_on:
      - switch.turn_off: sprinklers_1
      - switch.turn_off: sprinklers_2
      - switch.turn_off: sprinklers_3
      - switch.turn_off: sprinklers_4
      - switch.turn_off: sprinklers_6
      - delay: 
          minutes: 60
      - switch.turn_off: sprinklers_5

  - platform: gpio
    pin: GPIO33 # Q5 @ norvi iiot
    id: sprinklers_6
    name: "IrriZone 6"
    icon: mdi:sprinkler-variant
    on_turn_on:
      - switch.turn_off: sprinklers_1
      - switch.turn_off: sprinklers_2
      - switch.turn_off: sprinklers_3
      - switch.turn_off: sprinklers_4
      - switch.turn_off: sprinklers_5
      - delay: 
          minutes: 60
      - switch.turn_off: sprinklers_6

binary_sensor:
  - platform: gpio
    pin: GPIO36
    name: "Button"
    on_click:
    - min_length: 50ms
      max_length: 350ms
      then:
#        - script.execute: sprinklers_5
#        - script.wait: sprinklers_5
#        - script.execute: sprinklers_3
#        - script.wait: sprinklers_3
#        - script.execute: sprinklers_1
#        - script.wait: sprinklers_1
#        - script.execute: sprinklers_2
#        - script.wait: sprinklers_2
        - script.execute: sprinklers_off
    - min_length: 500ms
      max_length: 1000ms
      then:
#        - script.execute: sprinklers_4
#        - script.wait: sprinklers_4
        - script.execute: sprinklers_off
#        - switch.turn_on: relay_1

script:
  - id: sprinklers_off
    then:
      - switch.turn_off: sprinklers_1
      - switch.turn_off: sprinklers_2
      - switch.turn_off: sprinklers_3
      - switch.turn_off: sprinklers_4
      - switch.turn_off: sprinklers_5
      - switch.turn_off: sprinklers_6

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: /6
        then:
          - script.execute: sprinklers_off
      - seconds: 0
        minutes: 55
        hours: 22
        then:
          - switch.turn_on: sprinklers_3
      - seconds: 0
        minutes: 1
        hours: 0
        then:
          - switch.turn_on: sprinklers_4
      - seconds: 0
        minutes: 3
        hours: 1
        then:
          - switch.turn_on: sprinklers_5
          #- delay: 63 min
#          - script.wait: sprinkler_1
      - seconds: 0
        minutes: 5
        hours: 2
        then:
          - switch.turn_on: sprinklers_1
      - seconds: 0
        minutes: 29
        hours: 5
        then:
          - switch.turn_on: sprinklers_2
